### ISSUE TITLE
Undefined variable: this

### ISSUE THREAD

**Issue by dbashyal** [ProxiBlue/OrderSyncQueRunner#3]
Hi Lucas,

I am getting this error:

``` php
Notice: Undefined variable: this  in /app/code/community/ProxiBlue/OrderSyncQueRunner/Model/Cron.php on line 26
```

my IDE says: "$this is not accessible in static context."

**Comment by ProxiBlue** [comment]
@dbashyal Ooops ;)

Code was returning $this in static context. Corrected.
